apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: quangdvn/expiration
          imagePullPolicy: Always
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-serv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: REDIS_HOST
              value: expiration-redis-serv
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: expiration-serv
# spec:
#   selector:
#     app: expiration
#   ports:
#     - name: expiration
#       protocol: TCP
#       port: 4000
#       targetPort: 4000
