name: deploy-auth

on: 
  push:
     branches: 
       - main
     paths:
       - 'auth/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Image
        run: cd auth && docker build -t quangdvn/auth .
      - name: Log in Docker Hub
        run: docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        run: docker push quangdvn/auth
        
