name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - "infra/k8s/**"
      - "infra/k8s-prod/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Save new cluster
        run: doctl kubernetes cluster kubeconfig save quangdvn-ticketing
      - name: Get k8s nodes
        run: kubectl get nodes
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
